semana2/e-Commerce/e-Commerce/config/routes.rb
Rails.application.routes.draw do
 root :to => "articles#index"
 
 resources :articles
 resources :backpacks
end

semana2/e-Commerce/e-Commerce/app/models/article.rb
class Article < ActiveRecord::Base
end

semana2/e-Commerce/e-Commerce/app/models/backpack.rb
class Backpack < ActiveRecord::Base
end

semana2/e-Commerce/e-Commerce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

semana2/e-Commerce/e-Commerce/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
   		@article = Article.new
    end

    def edit
  		@article = Article.find(params[:id])
	end

    def create
        @article = Article.new(article_params)
        @article.save
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to root_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :model, :processorBrand, :ram, :price)
    end
end

semana2/e-Commerce/e-Commerce/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
	def index
		@backpacks = Backpack.all

	end

	def show
		@backpack = Backpack.find(params[:id])
	end

	def new
		@backpack = Backpack.new
	end

	def edit
  		@backpack = Backpack.find(params[:id])
	end


	def create
		@backpack = Backpack.new(backpack_params)
		@backpack.save
		redirect_to backpack_path(@backpack)
	end

	def destroy
  		@backpack = Backpack.find(params[:id])
  		@backpack.destroy

  		redirect_to backpacks_path
	end

	private
	def backpack_params
		params.require(:backpack).permit(:color, :capacity, :pockets, :waterproof)
	end
end 

semana2/e-Commerce/e-Commerce/app/helpers/application_helper.rb
module ApplicationHelper
end

semana2/e-Commerce/e-Commerce/app/helpers/articles_helper.rb
module ArticlesHelper
end

semana2/e-Commerce/e-Commerce/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

semana2/e-Commerce/e-Commerce/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>

   <p>
    <%= f.label :processorBrand %><br>
    <%= f.text_area :processorBrand %>
  </p>

   <p>
    <%= f.label :ram %><br>
    <%= f.text_area :ram %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


  <%= link_to 'Back', articles_path %>

semana2/e-Commerce/e-Commerce/app/views/articles/index.html.erb
<h1>Listing articles</h1> 
<% @articles.each do |article|%>
    <div><%= article.title %> 
		<%= link_to 'Show',  article_path(article)%>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

<p>
    <%= link_to 'New article', new_article_path %>
    <%= link_to 'Backpacks!', backpacks_path %>
</p>

semana2/e-Commerce/e-Commerce/app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>

   <p>
    <%= f.label :processorBrand %><br>
    <%= f.text_area :processorBrand %>
  </p>

   <p>
    <%= f.label :ram %><br>
    <%= f.text_area :ram %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to 'Back', articles_path %>
</p>

semana2/e-Commerce/e-Commerce/app/views/articles/show.html.erb
<h3>
  <strong>title:</strong>
  <%= @article.title %>
</h3>

<p>
  <strong>model:</strong>
  <%= @article.model %>
</p>

<p>
  <strong>processorBrand:</strong>
  <%= @article.processorBrand %>
</p>

<p>
  <strong>ram:</strong>
  <%= @article.ram %>
</p>

<p>
  <strong>price:</strong>
  <%= @article.price %>
</p>

<p>
<%= link_to 'Edit', edit_article_path(@article)%> 
<%= link_to 'Back', articles_path %>
</p>

semana2/e-Commerce/e-Commerce/app/views/backpacks/edit.html.erb
<h1>Editing backpack</h1>

<%= form_for :backpack, url: backpack_path(@backpack), method: :patch do |f| %>

  <p>
    <%= f.label :color %><br>
    <%= f.text_area :color %>
  </p>

  <p>
    <%= f.label :capacity %><br>
    <%= f.text_area :capacity %>
  </p>

  <p>
    <%= f.label :pockets %><br>
    <%= f.text_area :pockets %>
  </p>

  <p>
    <%= f.label :waterproof %><br>
    <%= f.text_area :waterproof %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', backpacks_path %>

semana2/e-Commerce/e-Commerce/app/views/backpacks/index.html.erb
<h1>Listing backpacks</h1> 
<% @backpacks.each do |backpack|%>
    <div><%= backpack.color %> 
        <%= link_to 'Show',  backpack_path(backpack)%>
        <%= link_to 'Edit', edit_backpack_path(backpack) %>
        <%= link_to 'Destroy', backpack_path(backpack), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

<p>
	<%= link_to 'articles!', articles_path %>
</p>
    
</p>

semana2/e-Commerce/e-Commerce/app/views/backpacks/new.html.erb
<%= form_for @backpack do |f| %>
  <p>
    <%= f.label :color %><br>
    <%= f.text_area :color %>
  </p>

  <p>
    <%= f.label :capacity %><br>
    <%= f.text_area :capacity %>
  </p>

  <p>
    <%= f.label :pockets %><br>
    <%= f.text_area :pockets %>
  </p>

  <p>
    <%= f.label :waterproof %><br>
    <%= f.text_area :waterproof %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

semana2/e-Commerce/e-Commerce/app/views/backpacks/show.html.erb
<h3>
  <strong>color:</strong>
  <%= @backpack.color %>
</h3>

<p>
  <strong>capacity:</strong>
  <%= @backpack.capacity %>
</p>

<p>
  <strong>pockets:</strong>
  <%= @backpack.pockets %>
</p>

<p>
  <strong>waterproof:</strong>
  <%= @backpack.waterproof %>
</p>

<p>
<%= link_to 'Edit', edit_backpack_path(@backpack)%> 
<%= link_to 'Back', backpacks_path %>
</p>

semana2/e-Commerce/e-Commerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>eCommerce </title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
  

<body>

<%= yield %>

</body>
</html>